In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.simplefilter('ignore')
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Dense
from keras.layers import Flatten
from keras.preprocessing.image import ImageDataGenerator
from tensorflow import keras


In [3]:
from keras.preprocessing.image import ImageDataGenerator
train = ImageDataGenerator(rescale = 1./255)
test = ImageDataGenerator(rescale = 1./255)

In [4]:
from tensorflow.keras.utils import img_to_array,array_to_img,load_img

dataaug = ImageDataGenerator(
        rotation_range=20,
        width_shift_range=0.3,
        height_shift_range=0.1,
        zoom_range=0.5,
        horizontal_flip=True,
        vertical_flip=True,
        fill_mode='nearest')

img = load_img("/Users/harsh/OneDrive/Desktop/paddy/blast.jpg")  
pic = img_to_array(img) 
pic = pic.reshape((1,) + pic.shape)

i = 0
for x in dataaug.flow(pic, batch_size=1,
                          save_to_dir='/Users/harsh/OneDrive/Desktop/paddy/test/blast', save_prefix='blast', save_format='jpeg'):
    i += 1
    if i > 50:
        break  

In [5]:
from tensorflow.keras.utils import img_to_array,array_to_img,load_img

dataaug = ImageDataGenerator(
        rotation_range=20,
        width_shift_range=0.3,
        height_shift_range=0.1,
        zoom_range=0.5,
        horizontal_flip=True,
        vertical_flip=True,
        fill_mode='nearest')

img = load_img("/Users/harsh/OneDrive/Desktop/paddy/BLB.jpg")  
pic = img_to_array(img) 
pic = pic.reshape((1,) + pic.shape)

i = 0
for x in dataaug.flow(pic, batch_size=1,
                          save_to_dir='/Users/harsh/OneDrive/Desktop/paddy/test/BLB', save_prefix='BLB', save_format='jpeg'):
    i += 1
    if i > 50:
        break  

In [6]:
from tensorflow.keras.utils import img_to_array,array_to_img,load_img

dataaug = ImageDataGenerator(
        rotation_range=20,
        width_shift_range=0.3,
        height_shift_range=0.1,
        zoom_range=0.5,
        horizontal_flip=True,
        vertical_flip=True,
        fill_mode='nearest')

img = load_img("/Users/harsh/OneDrive/Desktop/paddy/brownleaf.jpg")  
pic = img_to_array(img) 
pic = pic.reshape((1,) + pic.shape)

i = 0
for x in dataaug.flow(pic, batch_size=1,
                          save_to_dir='/Users/harsh/OneDrive/Desktop/paddy/test/brown leaf', save_prefix='brown leaf', save_format='jpeg'):
    i += 1
    if i > 50:
        break  

In [7]:
from tensorflow.keras.utils import img_to_array,array_to_img,load_img

dataaug = ImageDataGenerator(
        rotation_range=20,
        width_shift_range=0.3,
        height_shift_range=0.1,
        zoom_range=0.5,
        horizontal_flip=True,
        vertical_flip=True,
        fill_mode='nearest')

img = load_img("/Users/harsh/OneDrive/Desktop/paddy/sheath.jpg")  
pic = img_to_array(img) 
pic = pic.reshape((1,) + pic.shape)

i = 0
for x in dataaug.flow(pic, batch_size=1,
                          save_to_dir='/Users/harsh/OneDrive/Desktop/paddy/test/sheath', save_prefix='sheath', save_format='jpeg'):
    i += 1
    if i > 50:
        break  

In [8]:
from tensorflow.keras.utils import img_to_array,array_to_img,load_img

dataaug = ImageDataGenerator(
        rotation_range=20,
        width_shift_range=0.3,
        height_shift_range=0.1,
        zoom_range=0.5,
        horizontal_flip=True,
        vertical_flip=True,
        fill_mode='nearest')

img = load_img('/Users/harsh/OneDrive/Desktop/paddy/blast.jpg')  
pic = img_to_array(img) 
pic = pic.reshape((1,) + pic.shape)

i = 0
for x in dataaug.flow(pic, batch_size=1,
                          save_to_dir='/Users/harsh/OneDrive/Desktop/paddy/train/blast', save_prefix='blast', save_format='jpeg'):
    i += 1
    if i > 250:
        break  

In [9]:
from tensorflow.keras.utils import img_to_array,array_to_img,load_img

dataaug = ImageDataGenerator(
        rotation_range=20,
        width_shift_range=0.3,
        height_shift_range=0.1,
        zoom_range=0.5,
        horizontal_flip=True,
        vertical_flip=True,
        fill_mode='nearest')

img = load_img('/Users/harsh/OneDrive/Desktop/paddy/BLB.jpg')  
pic = img_to_array(img) 
pic = pic.reshape((1,) + pic.shape)

i = 0
for x in dataaug.flow(pic, batch_size=1,
                          save_to_dir='/Users/harsh/OneDrive/Desktop/paddy/train/BLB', save_prefix='BLB', save_format='jpeg'):
    i += 1
    if i > 250:
        break  

In [10]:
from tensorflow.keras.utils import img_to_array,array_to_img,load_img

dataaug = ImageDataGenerator(
        rotation_range=20,
        width_shift_range=0.3,
        height_shift_range=0.1,
        zoom_range=0.5,
        horizontal_flip=True,
        vertical_flip=True,
        fill_mode='nearest')

img = load_img('/Users/harsh/OneDrive/Desktop/paddy/brownleaf.jpg')  
pic = img_to_array(img) 
pic = pic.reshape((1,) + pic.shape)

i = 0
for x in dataaug.flow(pic, batch_size=1,
                          save_to_dir='/Users/harsh/OneDrive/Desktop/paddy/train/brown leaf', save_prefix='brown leaf', save_format='jpeg'):
    i += 1
    if i > 250:
        break  

In [11]:
from tensorflow.keras.utils import img_to_array,array_to_img,load_img

dataaug = ImageDataGenerator(
        rotation_range=20,
        width_shift_range=0.3,
        height_shift_range=0.1,
        zoom_range=0.5,
        horizontal_flip=True,
        vertical_flip=True,
        fill_mode='nearest')

img = load_img("/Users/harsh/OneDrive/Desktop/paddy/sheath.jpg")  
pic = img_to_array(img) 
pic = pic.reshape((1,) + pic.shape)

i = 0
for x in dataaug.flow(pic, batch_size=1,
                          save_to_dir='/Users/harsh/OneDrive/Desktop/paddy/train/sheath', save_prefix='sheath', save_format='jpeg'):
    i += 1
    if i > 250:
        break  

In [12]:
train_data = train.flow_from_directory('/Users/harsh/OneDrive/Desktop/paddy/train',
                                                 target_size = (100, 100),
                                                 class_mode = 'categorical')

test_data = test.flow_from_directory('/Users/harsh/OneDrive/Desktop/paddy/test',
                                            target_size = (100, 100),
                                            class_mode = 'categorical')

Found 2902 images belonging to 4 classes.
Found 609 images belonging to 4 classes.


In [13]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from keras.preprocessing.image import ImageDataGenerator


classifier = Sequential()

classifier.add(Conv2D(32, (3, 3), input_shape=(100, 100, 3), activation='relu'))


classifier.add(MaxPooling2D(pool_size=(2, 2)))

classifier.add(Conv2D(32, (3, 3), activation='relu'))
classifier.add(MaxPooling2D(pool_size=(2, 2)))

classifier.add(Flatten())


classifier.add(Dense(units=128, activation='relu'))
classifier.add(Dense(units=4, activation='softmax'))  

classifier.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])



classifier.fit_generator(
    train_data,
    steps_per_epoch=len(train_data),
    epochs=25,
    validation_data=test_data,
    validation_steps=len(test_data))





Epoch 1/25


91/91 [==============================] - 30s 309ms/step - loss: 0.1487 - accuracy: 0.9562 - val_loss: 6.0902e-05 - val_accuracy: 1.0000
Epoch 2/25
91/91 [==============================] - 18s 198ms/step - loss: 4.5641e-05 - accuracy: 1.0000 - val_loss: 1.7494e-05 - val_accuracy: 1.0000
Epoch 3/25
91/91 [==============================] - 18s 197ms/step - loss: 1.9626e-05 - accuracy: 1.0000 - val_loss: 1.3284e-05 - val_accuracy: 1.0000
Epoch 4/25
91/91 [==============================] - 18s 198ms/step - loss: 1.4195e-05 - accuracy: 1.0000 - val_loss: 1.0247e-05 - val_accuracy: 1.0000
Epoch 5/25
91/91 [==============================] - 18s 198ms/step - loss: 1.0363e-05 - accuracy: 1.0000 - val_loss: 7.5536e-06 - val_accuracy: 1.0000
Epoch 6/25
91/91 [==============================] - 18s 198ms/step - loss: 7.8180e-06 - accuracy: 1.0000 - val_loss: 6.0338e-06 - val_accuracy: 1.0000
Epoch 7/25
91/91 [==============================] - 18s 197ms/step - loss: 6.1500e-06 - accur

In [14]:
from keras.preprocessing import image
import numpy as np

# Load the image you want to predict
img_path = "/Users/harsh/OneDrive/Desktop/paddy/sheath.jpg"
img = image.load_img(img_path, target_size=(100, 100))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension
img_array /= 255.  # Rescale pixel values to [0, 1]

# Make predictions
predictions = classifier.predict(img_array)
print(predictions)

# Decode the predictions
class_indices = train_data.class_indices
reverse_indices = {v: k for k, v in class_indices.items()}
predicted_class = reverse_indices[np.argmax(predictions)]
print("Predicted class:", predicted_class)


1/1 [==============================] - 0s 140ms/step
[[2.5964699e-08 7.3599908e-09 1.1152823e-12 1.0000000e+00]]
Predicted class: sheath


In [18]:
from keras.preprocessing import image
import numpy as np

img_path = "/Users/harsh/OneDrive/Desktop/paddy/test/brown leaf/brown leaf_0_64.jpeg"
img = image.load_img(img_path, target_size=(100, 100))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)  
img_array /= 255.  


predictions = classifier.predict(img_array)
print(predictions)


class_indices = train_data.class_indices
reverse_indices = {v: k for k, v in class_indices.items()}
predicted_class = reverse_indices[np.argmax(predictions)]
print("Predicted class:", predicted_class)


1/1 [==============================] - 0s 28ms/step
[[9.8829738e-15 1.5632965e-07 9.9999988e-01 2.1451611e-10]]
Predicted class: brown leaf


In [19]:
img_path = "/Users/harsh/OneDrive/Desktop/paddy/BLB.jpg"
img = image.load_img(img_path, target_size=(100, 100))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)  
img_array /= 255.  


predictions = classifier.predict(img_array)
print(predictions)


class_indices = train_data.class_indices
reverse_indices = {v: k for k, v in class_indices.items()}
predicted_class = reverse_indices[np.argmax(predictions)]
print("Predicted class:", predicted_class)

1/1 [==============================] - 0s 35ms/step
[[1.0000000e+00 3.4413333e-11 5.7835381e-24 1.0856143e-11]]
Predicted class: BLB
